name: Build firmware
on:
  workflow_dispatch:  # can be triggered manually
  pull_request:
  push:               # automatically run on changes to following paths
    paths:
      - "config/*"
      - ".github/workflows/build.yml"


jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
